# Generated by Django 4.1.2 on 2022-10-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        # migrations.AddField(
        #     model_name='testmodel',
        #     name='email',
        #     field=models.CharField(blank=True, max_length=50),
        # ),

        # migrations.RunSQL("DROP DATABASE;"),
    ]
